### ISSUE TITLE
Write integration tests

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#100]
* Our unit tests only check that functions are called in the way that we expect. They don't check the actual output from any functions. 
* Write integration tests that check the output of functions using previous integration tests from make.py framework as a starting point.
* We should only test the integration of features if the user has explicitly specified this option in gslab_python (e.g., `python setup.py test_integration`).

**Comment by stanfordquan** [comment]
Task postponed to after sprint, will be assigned to Peter after onboarding.

**Comment by arosenbe** [comment]
Assigning myself so this doesn't silently get stale.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
Haven't started

**Comment by stanfordquan** [comment]
I propose to put this on the outline for next release and close the task for the time being.

**Comment by stanfordquan** [comment]
Closing this task and moving it to outline.
