### ISSUE TITLE
Prepare for 4.1.0 release. 

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#101]
Command center for the 4.1.0 release.

Sprint starts Monday, August 21 2017. Meetings are 9am each day in room 321 (except for Tuesday we'll be in room 224).  We may want to make adjustment for August 21 to meet earlier because of [the solar eclipse starting at 9am](https://www.timeanddate.com/eclipse/in/usa/palo-alto). 

I divided tasks into blocks. Tasks in the same blocks are supposed to be worked on at the same time, designed to minimize pull request conflicts and grouped by functionality. 

The blocks are:  **B**uilder (42h), **L**ogging (34h), **C**onfig (38h), **R**aw (25h), and Integration **T**est (30h) . I suggest we proceed: B L C R. 

# [gslab_python](https://github.com/gslab-econ/gslab_python/milestone/2)
| #    | Short name           | Status | Assignee | Block |
|------|----------------------|--------|----------|-------|
| #91  | large file commit    | Closed  |   FY      |  C     |
| #92  | stata exec           | Closed  |    QL     |    B   |
| #93  | top-level logs       | Closed |  FY      |   L    |
| #94  | builder logs         | Closed |   QL       |  L    |
| #95  | builder target check | Closed  |  FY       |   L    |
| #96  | LaTeX                | Closed  |  CY        |  B     |
| #97  | anything builder     | Closed  |  QL        |  B     |
| #98  | R syntax             | Closed |   FY       |  B     |
| #99  | cache reconfig       | Closed  |   AR       |    C   |
| #100 | integration tests    | Postponed  |   --      |    T  |
| #108 | unit tests    | Closed  |     CY     |    T  |
| #111, #126  | update release.py    | Closed, PR  |     FY, AR     |    C  |
| #122 | delete old GSLab tools | Closed | AR | C |
| #128, #131 | Make provenance faster and general | Closed | AR, AR | L | 
| #130 | Uncouple gslab_python and template | Closed |QL |C |

# [template](https://github.com/gslab-econ/template/milestone/1)
| #                      | Short name              | Status | Assignee | Block |
|------------------------|-------------------------|--------|----------|-------|
| gslab-econ/template#59 | raw data storage        | Closed   |    CY      |  R     |
| gslab-econ/template#60                    | raw data provenance     | Closed  |   QL       |  R    |
| gslab-econ/template#61                    | restructure yaml        | Closed  |   FY      |  L     |
| gslab-econ/template#62                    | separate top-level template     | Closed |  CY        |  B     |
| gslab-econ/template#63                    | remove dependencies     | Closed   |    CY      |   C    |
| gslab-econ/template#64                    | port example scripts    | Closed |    CY      |   L   |
| gslab-econ/template#65                    | automate dependencies   | Closed  |  AR        |   C    |
| gslab-econ/template#66                    | gslab_stata integration | Closed |   CY       |   L    |
| gslab-econ/template#67                    | release/lg              | Closed  |  QL        |    B   |
| gslab-econ/template#68                    | hyphens                 | Closed  |   QL       |  B     |
| gslab-econ/template#69                    | debrief                 | Closed  |    FY      |   C    |
| gslab-econ/template#70                    | MATLAB yaml             | Closed  |   FY       |   B   |
| gslab-econ/template#71                    | gencat                  | Closed |    FY      |  R     |
| gslab-econ/template#82                    | docs | Closed | AR | last |
| gslab-econ/template#86                    | Record inputs on SCons | Closed | AR | L | 

### meeting schedule
| day | time | room |
|-----|------|------|
| Mon | 8am  | #321 |
| Tue | 9am  | #224 |
| Wed | 9am  | #321 |
| Thu | 9am  | #321 |
| Fri | 9am  | #321 |

### Pull request
Squash merge into branch 4.1.0.

**Comment by stanfordquan** [comment]
@gentzkow , I have a draft plan for the sprint above. We can discuss this at Noodles tomorrow or next Monday if you'd like.

**Comment by gentzkow** [comment]
Great. Let's discuss at Noodles.

**Comment by gentzkow** [comment]
Re solar eclipse: How about if we move the Monday meeting to 8am?

**Comment by stanfordquan** [comment]
8am Monday sounds great, thanks Matt. Meeting schedule posted above.

**Comment by stanfordquan** [comment]
@yuchuan2016 @Shun-Yang please be reminded that we're having a meeting at 8 o'clock tomorrow, Monday Aug 21. Thanks!

**Comment by arosenbe** [comment]
@stanfordquan, @Shun-Yang, @yuchuan2016 

I'm back from vacation, and I've read through all the issue/PR threads. Any place it'd be particularly useful for me to jump in? I've only been assigned a **T** task.

**Comment by stanfordquan** [comment]
Sprint status: 3 remaining open tasks for `gslab_python` (cache reconfiguration, size_warning.py, integration tests), 5 remaining open tasks for `template` (debrief doc, dependency automation, limit dependencies, and two raw data tasks). 

We'll have 9am meetings in SIEPR third floor meeting room per usual. We are aiming to have the debrief meeting on Thursday, potentially not having completed integration tests.

**Comment by stanfordquan** [comment]
We'll be having the last meeting of this sprint at 9am today in the third floor meeting room.

**Comment by stanfordquan** [comment]
All tasks are complete. Pull requests are open in [template](https://github.com/gslab-econ/template/pull/85) and [gslab_python](https://github.com/gslab-econ/gslab_python/pull/125).

**Comment by stanfordquan** [comment]
Review tasks opened in #134 #135
