### ISSUE TITLE
Fix unit tests in the current builders

### ISSUE THREAD

**Issue by yuchuan2016** [gslab-econ/gslab_python#108]
After #92 #98 are merged, the unit tests fail for the R builder and Stata builder. We can fix them now or fix them after the rest are pulled in.

**Comment by yuchuan2016** [comment]
@Shun-Yang , can you explain a little about what's the meaning of the 2>&1 in the build you write?
```command = 'Rscript --no-save --no-restore --verbose %s %s > %s 2>&1' % (source_file, cl_arg, log_file)```

We need to also update the unit test for the builder. One step is to parse the command similar to [this](https://github.com/gslab-econ/gslab_python/blob/4.1.0/gslab_scons/tests/_test_helpers.py#L48). Could you take a look to see how we would rewrite this under `Rscript`? Thanks a lot!

**Comment by Shun-Yang** [comment]
@yuchuan2016 sure, Rscript output to stdout. I use `2>&1` to append stderr to stdout and write them both to `log_file`. I will take a look at the parsing code.

**Comment by yuchuan2016** [comment]
@Shun-Yang , great! Thanks. I think perhaps I can fix it (you can go ahead if you think it's more efficient for you to fix this). We also need to fix [this](https://github.com/gslab-econ/gslab_python/blob/bf7b5f0d414b20635c94511073fdee24bab1e91a/gslab_scons/tests/_side_effects.py#L37)

**Comment by Shun-Yang** [comment]
@yuchuan2016 I spent sometime staring at the parsing code. I'm afraid that I won't be much help on this. Maybe you can go ahead and fix these?

**Comment by yuchuan2016** [comment]
@Shun-Yang , no problem. I have fixed 2 out of 3 errors in the R builder. I have one more question related to the last one. Do you have any particular reason why you delete [these lines](https://github.com/gslab-econ/gslab_python/blob/519e2cfa3a651579b2a7055764d74ae63b6bd4b0/gslab_scons/builders/build_r.py#L41)? Thanks!

**Comment by Shun-Yang** [comment]
@yuchuan2016 , the `cl_arg` for `R CMD BATCH` is different from `Rscript`. For `R CMD BATCH`, if you want to pass command line arguments you need to do `'--args  argument1 argument2'`. For `Rscript`, you can directly pass in by `argument1 argument2`.

**Comment by yuchuan2016** [comment]
@Shun-Yang , thanks! I will change the tests correspondingly.

**Comment by yuchuan2016** [comment]
Pull request in #109.
