### ISSUE TITLE
Revisit unit tests after sprint

### ISSUE THREAD

**Issue by yuchuan2016** [gslab-econ/gslab_python#112]
Follow #109. Need to update unit tests after we make all changes outlined in https://github.com/gslab-econ/gslab_python/issues/101#issue-249128581.

**Comment by arosenbe** [comment]
Assigning myself so this doesn't silently get stale.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by stanfordquan** [comment]
I propose to put this on the outline for next release and close the task for the time being.

**Comment by stanfordquan** [comment]
Closing this task and moving it to outline.
