### ISSUE TITLE
Delete old local gslab_python versions upon both installation methods

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#122]
At the moment a developer/user can install gslab_python in two ways:

1) Clone gslab_python and run `python setup.py install clean`

2) Clone template (as of 4.1.0) and run `python config/config_python.py`. 

The problem is that 1) writes the `egg` version into `site_package` and 2) writes both the `egg` and the subfolders (`gslab_blahblah`) into `site_package`. What this leads to is the following behavior:

a) Install gslab_python using 2)

b) Install different version of gslab_python using 1)

Now the versions of gslab_python on your computer are out of sync.

Our solution: remove *both* the `egg` and the subfolders upon installation of gslab_python using either method. Implemented by a search and destroy function in `setup.py`, then test whether `python config/config_python.py` properly runs that script when installing `gslab_python`.

**Comment by arosenbe** [comment]
We want to warn the user, explain what's going on, and ask for permission before search and destroy. Also make sure this works on Windows (no idea about redirection in that setting).

**Comment by arosenbe** [comment]
Under PR at #123. What a fun number.

**Comment by arosenbe** [comment]
PR passed at #123. 

`setup.py` now checks for any gslab-stamped packages (or gencat) in the default package installation location and deletes whatever it finds.
