### ISSUE TITLE
Limit make_provenance() run time

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#128]

**Comment by arosenbe** [comment]
Need to ensure appropriate number of new lines when writing readme to provenance. Need to ensure the syntax works on windows.

**Comment by arosenbe** [comment]
The find_for_me option in append_sub_provenance can be slow in large repositories. I'm also no longer sure we need the function if we're going to be running from the SConsctruct each time.

**Comment by arosenbe** [comment]
Balled into #131. Summary comment.

Enforces a binding file limit on the walk through the directory whose content is being recorded.

**Comment by arosenbe** [comment]
Work completed. See https://github.com/gslab-econ/gslab_python/issues/131#issuecomment-327942840 for summary.
