### ISSUE TITLE
Propose improvements to gslab_python release schedule

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#129]

**Comment by arosenbe** [comment]
Assigning everyone so this doesn't silently get stale

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by arosenbe** [comment]
No work done yet.

**Comment by Shun-Yang** [comment]
No work done yet.

**Comment by Shun-Yang** [comment]
No work done yet. (We probably should just spend an hour today to discuss a plan @arosenbe @stanfordquan @yuchuan2016 )

**Comment by Shun-Yang** [comment]
No work done yet.

**Comment by Shun-Yang** [comment]
No work done yet. (We probably should just spend an hour today to discuss a plan @arosenbe @stanfordquan @yuchuan2016 )

**Comment by stanfordquan** [comment]
[Against all odds](https://www.youtube.com/watch?v=NcwUtNdLFrs), the RA's had a meeting today to discuss the GSLab softwares release schedule. The three main tradeoffs that we perceive in managing releases are:

1. If there is a bug that makes GSLab softwares essentially unusable to a PI somewhere, we must fix and make a release ASAP.

2. It's costly to the user when we make an update (since they have to update template to accommodate new gslab_python and to install new gslab_python)

3. We don't often have dedicated stretches of time to roll out a new version

We suggested that the lab aims for the following:

- One "major release" every six months. New features and changes in the template go here. This release is "paired" (both template and gslab_python)

- PI-breaking bugs still must be fixed immediately, but we will exhaust options to fix it in gslab_python before attempting a solution in template. Ideally we will only make a gslab_python release for these.

We think that this schedule mitigates the user-cost issue since we are not making frequent updates _and_ when we make unscheduled bug fixes, we make them in the least costly way possible (fixing things in the kitchen rather than front of house, since users only need to run `pip install *new versions*` rather than have to follow instructions to update template).

In our (relatively limited) experience of working in GSLab, we often can find at least one stretch of time with less economics workload to dedicate to gslab_python every six months, hence that suggested time window.

**Comment by stanfordquan** [comment]
@gentzkow @jmshapir please see the comment above. Thanks!

**Comment by jmshapir** [comment]
The proposed schedule works for me, thanks.

**Comment by gentzkow** [comment]
I definitely like the second bullet (trying wherever possible to only make backwards-compatible changes in gslab_python). 

I think ongoing major releases that break the old template are very costly as you say. It's particularly bad if we are not going to want to go back and update older repositories so it means with high probability past repositories cannot be run with current code. What do you guys think about making a stronger commitment that we are going to maintain backwards compatibility in subsequent releases, with the possible exception of major changes that will happen more like every couple of years?

It might be worth thinking ahead to what kinds of issues are most likely to make this infeasible and trying to catch them ahead of time.

**Comment by stanfordquan** [comment]
I agree with the backward-incompatibility issue. In the past, virtually any update  on the template (e.g. a syntax change) is backward-incompatible since an existing user will have to switch to the new syntax. Now we will commit to handling the old case as well as the new case.

**Comment by gentzkow** [comment]
To be clear, I don't think it's fatal to have incompatible changes to the template. But we don't want these to be reflected in gslab_python in a way that causes existing repos based on old templates to break.

That said, we do want to commit to template changes going forward that are as easy as possible to implement in existing repos.

**Comment by stanfordquan** [comment]
Got it, Matt. How do you suggest we go forward from this task? I can put the above deliverable (with suggested modifications) in the wiki, or we can go further and set a release date (some time in July) and roll proposed new features into the next release date as well.

**Comment by gentzkow** [comment]
The other issue that led to this task is the cost of releases themselves.

Let's say I make a small bug fix in gslab_python that doesn't cause any backwards incompatibility. What are the steps I'd need to take to release it and propagate it out to the team? Anything that would prevent me doing that in <5 mins?

I think in the past we were batching changes into large releases and viewing frequent releases as costly. Maybe that was all because of backwards compatibility issues, but at some point it seemed like it was also the release process being cumbersome. Maybe this was back when we were releasing in a different way?

**Comment by stanfordquan** [comment]
Matt, your impression (5 mins) is consistent with ours. You need to make the change, release it, and then send out an email ("hey there's a new version!") and then everyone will pip install it.

Frequent releases are only costly insofar if we make bug fixes in template (because by definition template changes are backward-incompatible).

**Comment by arosenbe** [comment]
No work on implementation yet.

**Comment by gentzkow** [comment]
I think we are all agreed on the plan. Why don't you write it up in the RA manual.

I'm going to assume this is active, and so (i) head revision of gslab_python will be our current version, all active repos should run with it, and whenever there are small bug fixes the modification will be pushed out immediately (with a note sent around to the team that they should update). Let me know if any of that is not right.

**Comment by stanfordquan** [comment]
I wrote it up [here](https://github.com/gslab-econ/ra-manual/wiki/Template-and-GSLab-Python-Development). 

@Shun-Yang , can you please take a quick look there and see if you agree with everything I wrote and way I wrote it? You can close the issue as giving the OK. Thanks!
