### ISSUE TITLE
Check and enforce principle for uncoupling gslab_python from gslab template

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#130]
Our principle is that folder paths in `gslab_python` should have defaults that match the folder structure in `template`, but these should be easily modified. 

This task should double check that this principle is upheld in `gslab_python` codebase

**Comment by arosenbe** [comment]
@stanfordquan, @yuchuan2016, @Shun-Yang 

Anyone want to do this task? I'm probably not optimal since I wasn't here for a lot of the code changes at the start of the sprint. It's also the last item for the milestone before the PIs take another look.

**Comment by stanfordquan** [comment]
Collecting points where we couple directory structure with `gslab_python`.
