### ISSUE TITLE
Change provenance to state_of_inputs

### ISSUE THREAD

**Issue by arosenbe** [gslab-econ/gslab_python#131]
We currently create static provenance files at release. We want these to be dynamic and produced at runtime (on `scons`). The idea is to record the state of local copies of external inputs. See https://github.com/gslab-econ/template/issues/86#issuecomment-327526608 for details.

The goal of this task is to implement this change. It will, among other things, purge provenance creation from the release procedure. 

This task subsumes #128.

**Comment by stanfordquan** [comment]
PR in #132

**Comment by arosenbe** [comment]
PR passed at #132. Summary comment
* Destroy all references to provenance.py
* Port walk engine from provenance.py to [record_dir.py](https://github.com/gslab-econ/gslab_python/blob/e8b0ecdb27513768fab83a5978ff975ec27a1306/gslab_scons/record_dir.py) 
* Create record_dir.py to record some characteristics of files in a directory and append the characteristics to a log.
