### ISSUE TITLE
Logging breaks if a folder has space in its name

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#147]
This is because the bash command breaks when you pass a folder with space in its name as we don't wrap it in quotes.

```bash
rclone copy gsbox:gslab_data/raw/divergence/gentzkow_aer_2007 build/external/gentzkow_2007 > build/external/gentzkow_2007/raw data/sconscript_export_gentzkow.log 2>&1
```

It's fairly standard to force a user to not have space characters in file and folder names, so I'm fine with not addressing this issue and instead making a note in template saying "we don't do this."

**Comment by arosenbe** [comment]
Thanks @stanfordquan! Fix above.
