### ISSUE TITLE
Add PyTest runner dependency

### ISSUE THREAD

**Issue by AakaashRao** [gslab-econ/gslab_python#153]
I was installing GSLab Python on a new machine and needed to install [Pytest-Runner](https://github.com/pytest-dev/pytest-runner) via Pip before I could successfully run `pip install git+https://git@github.com/gslab-econ/gslab_python.git@master`. This dependency is not listed in the `readme.md`.

**Comment by arosenbe** [comment]
@AakaashRao, that dependency is tracked in `setup.py`

https://github.com/gslab-econ/gslab_python/blob/7093ee9e6740a998a8f2503d74343bce7813d54c/setup.py#L74

 Funny that it was giving you grief though: 

<img width="1019" alt="screen shot 2018-08-16 at 4 44 03 pm" src="https://user-images.githubusercontent.com/19935793/44240564-a36de780-a173-11e8-81be-5870d632fd9a.png">

I'm going to close, but LMK if this becomes an issue again.
