### ISSUE TITLE
#154 Installation is unsuccessful every other time

### ISSUE THREAD

**Issue by DavidRitzwoller** [gslab-econ/gslab_python#154]
Opening an issue for the following error:
![screen shot 2018-07-06 at 2 13 51 pm](https://user-images.githubusercontent.com/35339599/42400589-ff9defcc-8126-11e8-8563-91c97eebb84f.png)

The bug may be localized to anaconda users.

**Comment by DavidRitzwoller** [comment]
@arosenbe confirms that the issue is not confined to anaconda users. I am investigating whether it is associated with the [deletion of old versions of GSLab_Tools. ](https://github.com/gslab-econ/gslab_python/issues/122)

**Comment by stanfordquan** [comment]
Pulled into dev branch on #155 🦉
