### ISSUE TITLE
Missing import in matlab builder?

### ISSUE THREAD

**Issue by jmshapir** [gslab-econ/gslab_python#157]
@arosenbe @DavidRitzwoller is it possible we're missing an ```import sys``` from the top of [build_matlab.py](https://github.com/gslab-econ/gslab_python/blob/7093ee9e6740a998a8f2503d74343bce7813d54c/gslab_scons/builders/build_matlab.py)?

**Comment by arosenbe** [comment]
Yes. We are missing `import sys`. We'll fix it up today.

**Comment by arosenbe** [comment]
Pull request for @z-y-huang in #158.
