### ISSUE TITLE
Error parsing gslab_tools version

### ISSUE THREAD

**Issue by jmshapir** [gslab-econ/gslab_python#164]
Using gslab_tools v. 4.1.2
My config_global calls for at least v. 4.1.1
I get the error below
Any thoughts?

```

C:\Users\jshapir1\Documents\GitHub\Skills\paper_slides>python run.py
scons: Reading SConscript files ...
TypeError: sequence item 0: expected string, int found:
  File "C:\Users\jshapir1\Documents\GitHub\Skills\paper_slides\SConstruct", line
 12:
    [mode, cache_dir, CONFIG, executable_names, prereqs, pythonpath] = configura
tion(ARGUMENTS)
  File "../config\configuration.py", line 55:
    gslab_vers = CONFIG['global']['gslab_version'])
  File "C:\python27\lib\site-packages\gslab_scons\check_prereq.py", line 33:
    % ('.'.join(installed_version), '.'.join(required_version))
```

**Comment by Shun-Yang** [comment]
@jmshapir Do you mind changing ` 4.1.1` to ` 4.1.2` in `config_global.yaml`? 

I can reproduce this bug by changing my version number to ` 4.1.1`. I'm not sure if this error is intentional, but the error message is definitely confusing. I'll take a look at what's happening.

**Comment by jmshapir** [comment]
@Shun-Yang yup, that change kills this error.

**Comment by DavidRitzwoller** [comment]
@jmshapir @Shun-Yang I found the bug causing the error. There was an issue with how we were parsing the version number for our package. 

| Before | After |
|---|---|
| <img width="578" alt="screen shot 2018-10-16 at 10 47 13 pm" src="https://user-images.githubusercontent.com/35339599/47064798-adbd5980-d195-11e8-9c3b-e0efca1fc44b.png"> | <img width="777" alt="screen shot 2018-10-16 at 10 47 28 pm" src="https://user-images.githubusercontent.com/35339599/47064780-a5651e80-d195-11e8-9ae8-aff1ba694a76.png"> |

There is now an informative error message when using an outdated version of `gslab_python`.

<img width="751" alt="screen shot 2018-10-16 at 10 44 38 pm" src="https://user-images.githubusercontent.com/35339599/47064863-dd6c6180-d195-11e8-9d15-cb778ec9da3b.png">

**Comment by DavidRitzwoller** [comment]
Summary: In this issue, we fixed an error in how the version number of `gslab_python` is being read.
