### ISSUE TITLE
SaveData python future warning: .fillna()

### ISSUE THREAD

**Issue by zhizhongpu** [gslab-econ/gslab_python#176]
Running SaveData.py results in:
> SaveData.py:48: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
>   var_stats = df.describe(include='all').transpose().fillna('')

**Comment by liaochris** [comment]
In this issue, we resolved warnings about downcasting object types when using `fillna()` by updating [`SaveData.py`](https://github.com/gslab-econ/gslab_python/blob/41c620b3274b012b4b1a28995a5242e1d3cf887b/gslab_misc/SaveData/SaveData.py).

- Permanent version of [issue subfolder](https://github.com/gslab-econ/gslab_python/tree/98a0d73c5c10ce377b736daf7448756d72bcf771/issue176_fillna_warning) used for testing
- Latest version of issue commit: https://github.com/gslab-econ/gslab_python/commit/aad359b4ceb6d83d2f82444b903fd4cc28bec0f8
