### ISSUE TITLE
SaveData does not take pathlib paths

### ISSUE THREAD

**Issue by zhizhongpu** [gslab-econ/gslab_python#177]
When `out_file` or `log_file` take in Path objects, SaveData runs into error:

```
TypeError: expected string or bytes-like object, got 'PosixPath'
```

The temporary fix is to first transform these arguments using `str()` before passing them into the function. 

Here we explore the possibility to allow SaveData to take `PosixPath` objects directly.

**Comment by liaochris** [comment]
Updated from master in https://github.com/gslab-econ/gslab_python/commit/e3d66eb5d78cd077b1c7cad056c51204c6d9bdd0

**Comment by liaochris** [comment]
In this issue we updated [`SaveData.py`](https://github.com/gslab-econ/gslab_python/blob/e3d66eb5d78cd077b1c7cad056c51204c6d9bdd0/gslab_misc/SaveData/SaveData.py) to take in Path objects as inputs for `out_file` and `log_file`. 

latest version of issue branch: https://github.com/gslab-econ/gslab_python/commit/0cb01cd51fa5da74306da0c95c45c80fec49f565
