### ISSUE TITLE
SaveData does not move key columns to the left

### ISSUE THREAD

**Issue by zhizhongpu** [gslab-econ/gslab_python#181]
The [R version of `SaveData()`](https://github.com/gslab-econ/gslab_r/blob/master/SaveData/R/SaveData.R) reorders columns so that key columns are placed on the left side of the .csv. This function does not exist in the Python version. Here we fix the issue.

**Comment by liaochris** [comment]
From https://github.com/gslab-econ/gslab_python/issues/184, an identical issue. 
> `r::SaveData` automatically moves the key columns in the left of the saved file. It would be great to have this functionality in `python::SaveData`.
> 
> It would be great to put this functionality under an optional argument that is true by default.

**Comment by liaochris** [comment]
In this issue, we updated [`SaveData.py`](https://github.com/gslab-econ/gslab_python/blob/663d32682f2024d54598ba5f2f181998e9f27d91/gslab_misc/SaveData/SaveData.py) to export keys on the left hand side of the data and added relevant [testcases](https://github.com/gslab-econ/gslab_python/blob/663d32682f2024d54598ba5f2f181998e9f27d91/gslab_misc/SaveData/tests/test_main.py). 

Latest version of issue branch: https://github.com/gslab-econ/gslab_python/commit/663d32682f2024d54598ba5f2f181998e9f27d91
