### ISSUE TITLE
Create SaveData library 

### ISSUE THREAD

**Issue by zhizhongpu** [gslab-econ/gslab_python#190]
Problem: right now, our method of adopting SaveData python is to copy the latest version of SaveData.py to project directory and import the script itself through, say, 

```
from source.lib.SaveData import SaveData
```

Potentially making SaveData a python package could facilitate installing and upgrading. For example, in R: SaveData, a user could simply:
```
library(devtools)
install_github("gslab-econ/gslab_r/SaveData")
```

so here we explore the possibility of making SaveData a package.

**Chris:** For example, when updates to `SaveData` in python are made, one can simply run `pip install -U SaveData`

**Comment by liaochris** [comment]
Note that in `gslab-econ/gslab_r`, `SaveData` is in a separate foder from `gslab_misc`

**Comment by liaochris** [comment]
@jmshapir fyi

**Comment by liaochris** [comment]
Created [`190-create-savedata-library`](https://github.com/gslab-econ/gslab_python/tree/190-create-savedata-library)` branch, following [this guide](https://packaging.python.org/en/latest/tutorials/packaging-projects/) for project creation

**Comment by liaochris** [comment]
Updates - to use savedata library, follow these steps (taken from readme)
1. Install using `pip install --index-url https://test.pypi.org/simple/ --no-deps savedata-gslab`
2. In the import section of your script/notebook, include `from SaveData_GSLab.SaveData import SaveData`
3. `SaveData` has exactly the same functionality and usage style as before: 
 - `SaveData(df, keys, out_file = out_file, log_file = log_file, append = False, sortbykey = True)`

**Comment by liaochris** [comment]
@zhizhongpu I saw those, but I'm unable to test whether we can use `SaveData` as an import from `gslab_python` because the pip install commands that are referenced don't work for me.

**Comment by liaochris** [comment]
@jmshapir  After discussion, I propose and @zhizhongpu agrees that we create a python library (called `gslab_python`, `jmslab_python` or whatever else you think works) that contains the following two modules (with more than can be added as we see fit)
- SaveData
- TableFill
These are currently two python scripts that we copy and update in all our projects as we update them in `GSLab/gslab_python`, which seems like a recipe for something to go wrong. We're also happy to try and find a way to incorporate it into the `GSLab/gslab_python` framework, although our initial assessment is doing that will be more time consuming. 

We're wondering what you think and if you agree with the proposal, where it should be built (JMSlab or GSLab) and what it should be called

**Comment by jmshapir** [comment]
@liaochris thanks! Let's discuss at our next meeting so I can better understand the tradeoffs. Can you remind me to raise this when we meet?

**Comment by liaochris** [comment]
In this issue, we discussed whether to make a python library for `SaveData`. We decided instead to move `SaveData.py` to `JMSLab/Template`. The discussion continues in https://github.com/JMSLab/Template/issues/102
