### ISSUE TITLE
Create Lyx scanner

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/gslab_python#23]
See https://github.com/gslab-econ/template/issues/19#issuecomment-259721983 and http://www.scons.org/doc/2.0.1/HTML/scons-user/c3833.html. Should be implemented in gslab_scons.

**Comment by yuchuan2016** [comment]
On hold.

**Comment by yuchuan2016** [comment]
Summary:

Add a function in `gslab_scons.misc` #50 . Add two lines in `template/SConstruct` gslab-econ/template#29. Allow users to specify the extensions they want to scan in the `.lyx` file. The scanner is recursive.

Closing this task.
