### ISSUE TITLE
Implement "paths.txt" solution

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/gslab_python#29]
See comment below.

**Comment by lboxell** [comment]
@stanfordquan, I'm going to take a stab at this today.

**Comment by lboxell** [comment]
Notes:
 - Stata: 
    - See [here](https://github.com/sergiocorreia/stata-misc/blob/75a8b251bec02ba590c862cc395c4b95077d8a95/yaml.ado) for a .ado file that seems to parse yaml files.
 - R: https://cran.r-project.org/web/packages/yaml/yaml.pdf
 - Python: [pyyaml](http://pyyaml.org/)

**Comment by lboxell** [comment]
@gentzkow @jmshapir @arosenbe @stanfordquan @M-R-Sullivan @yuchuan2016.

My current proposed setup for our "paths.txt" solution can be seen [here](https://github.com/gslab-econ/template/pull/35/files) in the template. I was able to construct something without having to create any new modules/packages. The stata ado file is not the most refined, but it should work for our purposes. 

Let me know if this doesn't align with what we were envisioning.

**Comment by jmshapir** [comment]
@lboxell the Stata/R libraries for yaml interaction seem nice to me.

**Comment by gentzkow** [comment]
@lboxell: This looks very slick to me. Good work!

> --

Matthew Gentzkow
Professor of Economics
Stanford University

**Comment by lboxell** [comment]
Closing task.

Summary:
 - Updated template ([here](https://github.com/gslab-econ/template/pull/35#issuecomment-277465418)) to use the "paths" interface for defining relatives paths using yaml files.
 - Follow up task is https://github.com/gslab-econ/gslab_python/issues/57 to fix windows bugs discovered in the PR of this issue.
