### ISSUE TITLE
Create release.py

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/gslab_python#33]
See https://github.com/gslab-econ/template/issues/19#issuecomment-260826983. Should either live in gslab_python or at the root of the template and its helpers live in gslab_python. 

See the next two comments also.

**Comment by stanfordquan** [comment]
With #36 pulled in, is this issue completed?

**Comment by M-R-Sullivan** [comment]
@stanfordquan - No, as I still need to look into an error that @arosenbe encountered  in [this issue's /template/ pull request](https://github.com/gslab-econ/template/pull/21). If the completion of this issue is a prerequisite for a priority of yours, I can focus on resolving this error in coming work hours.

**Comment by stanfordquan** [comment]
Not at all, don't worry. I looked over the commit history and looks like unit tests are done and dusted, so I don't need to work on that! Thanks.

**Comment by M-R-Sullivan** [comment]
This issue has passed peer review at #36 and https://github.com/gslab-econ/template/pull/21. So I am closing it now.

**Summary**
- I released GSLab Tools 3.0.0, which adds functionality for making releases from SCons/GitHub repositories to GitHub and to Google Drive to `gslab_scons`. This functionality is described in [gslab_scons/README.md](https://github.com/gslab-econ/gslab_python/blob/master/gslab_scons/README.md).
- The `release.py` script `gslab_scons` checks that versioned files are not overly large and that the repository from which the user is making a release is up-to-date (i.e. that SCons has built all of the repository's targets and that changes have been committed with git). 
- I revised code in the [large template](https://github.com/gslab-econ/template/tree/large_template) to be compatible with `gslab_scons`'s new release functionality.
