### ISSUE TITLE
Create state of repo logger

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/gslab_python#34]
See https://github.com/gslab-econ/template/issues/19#issuecomment-260826983 and https://github.com/gslab-econ/template/issues/19#issuecomment-260829667. Should live in gslab_python and, by default, run after every scons run. Should be printed to sconstruct (or it's own) log file.

There should be some safety checks to ensure it doesn't take forever to run through millions of files and shouldn't do any computational steps (i.e., compute hashes).

**Comment by lboxell** [comment]
Need to confirm that if you do `sconsign .sconsign.dblite` as the last step of the build process that it outputs the same thing as doing it after the build process has finished (up to being self-documenting).

**Comment by lboxell** [comment]
Note that .sconsign.dblite is edited after the build finishes, so `sconsign .sconsign.dblite` isn't that informative.

**Comment by lboxell** [comment]
@gentzkow @jmshapir @arosenbe @stanfordquan @yuchuan2016 @M-R-Sullivan:

The current output for the state_of_repo logger looks like [this](https://github.com/gslab-econ/template/blob/e02ee63f7bd7688cb7964570d7dd46bcd6a0f07e/state_of_repo.log). 

I currently print two things: (1) GIT STATUS (last git commit and files that have been modified since then) and (2) The modification time and size of all files at or below the root directory where scons was run from (with a limit of 10 files per subdir). 

I'm not sure there is a way to use information in the .sconsign.dblite because this seems to get edited after all the build steps have finished (unless we make the state_of_repo.log creation separate from the main `scons` run).  

The state_of_repo.log gets completely re-written after each run. 

One thing that currently can't be determined from this is the scons tree. It looks like it will take a bit of work to print the scons tree when scons is actually running (instead of doing it manually after the run), but I can try and do this if people think it will be useful.

Let me know if you guys have any thoughts on changing/improving this.

**Comment by jmshapir** [comment]
@lboxell this looks to me like the right balance of effort and reward for now. If printing the tree is very easy it would be a nice addition but it's also fine with me to leave it on the to-do list and move forward with this.

**Comment by gentzkow** [comment]
I think this is a good place to stop on this for now.
-- 

Matthew Gentzkow
Professor of Economics
Stanford University

**Comment by lboxell** [comment]
Closing task.

Summary:
 - Created new [release](https://github.com/gslab-econ/gslab_python/releases/tag/v3.0.3) that implmements a state of repo logger.
 - Added note about adding scons tree to wiki [outline](https://github.com/gslab-econ/gslab_python/wiki/Outline/d1cb8ababc2e6beba59bf4448455c24362c1e6ac).
 - Updated template [here](https://github.com/gslab-econ/template/commit/0b3d7901dfe330fd90e22dd9074405b796a3cb21).
