### ISSUE TITLE
Write Windows-specific builder unit tests

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#39]
Follow up from #37 a number of tests were found out to be incompatible with Windows machines. This task changes that.

**Comment by stanfordquan** [comment]
Task on hold until #45 is done

**Comment by stanfordquan** [comment]
On hold with trans and politext tasks. Also need #45.

**Comment by lboxell** [comment]
@stanfordquan:

 Note that #45 makes unit tests system independent. So, in some sense this task doesn't seem necessary. I think we'll want to have system dependent 'integration' tests, but that may be something for the next round of template/scons changes. Perhaps, this would be a good thing to put on the outline for the next round along with a general note about implementing 'integration' tests?

**Comment by stanfordquan** [comment]
Good idea. I'll put it on the outline.
