### ISSUE TITLE
Publicizing releases

### ISSUE THREAD

**Issue by jmshapir** [gslab-econ/gslab_python#42]
@lboxell @arosenbe @M-R-Sullivan @stanfordquan my reading is that the [template](https://github.com/gslab-econ/template) depends on gslab-python but that, since we deprecated support for PyPI, gslab-python's releases are no longer being made public.

Is that correct?

If so let's use this issue to discuss how best to publicize gslab-python. One option would be to make the whole repo public. Another would be to publicize only the releases. From [this post](http://stackoverflow.com/questions/26217941/can-i-make-releases-public-from-a-private-github-repo) it looks like there is no direct way to publicize a release from a private repo but there are some workarounds.

**Comment by lboxell** [comment]
Closing task.

Summary:
 - Repo is public. 
 - Added link to license in repo readme.
 - Updated RA manual [here](https://github.com/gslab-econ/ra-manual/wiki/Repository-Organization/18d998180f2cc9157cc32c388ef503c972577cef)
