### ISSUE TITLE
Dependency on package "requests"

### ISSUE THREAD

**Issue by jmshapir** [gslab-econ/gslab_python#43]
@lboxell @arosenbe @M-R-Sullivan @stanfordquan it looks like gslab-python depends on a package called "requests" that is not automatically installed by ```setup.py```.

Is this intended behavior?

**Comment by arosenbe** [comment]
A later commit overwrote the change I made in this issue: reopening to reimplement the change. See [here](https://github.com/gslab-econ/template/pull/26#issuecomment-274103638) for context.

**Comment by arosenbe** [comment]
Now under PR at #48.

**Comment by arosenbe** [comment]
Summary comment
  *  Add `requests` module as a dependency in `setup.py`.
  *  Ensure no other undocumented dependencies exist. 

  *  Readd `requests` module as a dependency in `setup.py` after being overwritten by later commit.
