### ISSUE TITLE
Add Dropbox interface module

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/gslab_python#52]
See https://github.com/gslab-econ/admin/issues/87#issuecomment-275005375. We'll want a dropbox module that can upload and download both files and folders (recursively) from a specific revision. 

We'll then want to use these functions in gslab_scons for release and getting raw/externals, along with the ability to easily upload files to dropbox from command line.

**Comment by lboxell** [comment]
@gentzkow, I'm working on setting up the dropbox interface and, in order to obtain an OAuth token for testing on our GSLab dropbox acct, I need to be an administrator. Is that something you can add me as for this?

**Comment by gentzkow** [comment]
Sure. Should be done.
-- 

Matthew Gentzkow
Professor of Economics
Stanford University

**Comment by lboxell** [comment]
@gentzkow, confirmed.

**Comment by lboxell** [comment]
Note that using a person app and having the user created the token via the online interface works when you build the app to access the GSLab dropbox acct, so I actually won't need admin access (nor should anyone else).

**Comment by lboxell** [comment]
@arosenbe:

Have you seen http://rclone.org/ before? Any reason you think we should create our own module instead of using rclone?

**Comment by lboxell** [comment]
Was able to use it on RCC with the following installation (the instructions on their website don't work because they require sudo or GOPATH setup).

### RCC Installation


curl -O http://downloads.rclone.org/rclone-current-linux-amd64.zip
unzip rclone-current-linux-amd64.zip
cd rclone-*-linux-amd64
mkdir /home/$USER/.rclone/bin
cp rclone /home/$USER/.rclone/bin
chmod 755 /home/$USER/.rclone/bin/rclone
PATH=$PATH:/home/$USER/.rclone/bin # Might want to add this permenantly

**Comment by lboxell** [comment]
I was able to transfer ~25GB of files to RCC from dropbox in roughly 6 minutes.

**Comment by lboxell** [comment]
@arosenbe,

Since you're the one who is most familiar with dropbox, I'm sending this to you to PR. My proposal is that we scrap gslab_dropbox and just use `rclone`.  

Apparently, "we" were aware of rclone at [one point](https://github.com/gslab-econ/admin/blob/ebf273130485a4c13bfb20c8a52147c399b5ec2b/issues/34/admin-34.md) and [here](https://github.com/gslab-econ/admin/blob/22b39cc25fc3bab2cac55a75a5eb83fd4ed9025e/_issues/9/admin-9.md). It seems like rclone can do what we want and we can interface with it directly in gslab_scons instead of creating a separate module for it.

**Comment by lboxell** [comment]
Ownership transfer on drive is restricted to in-domain transfers. The below is the result of me tryign to transfer to Jesse: 
<img width="577" alt="screen shot 2017-01-26 at 6 14 44 pm" src="https://cloud.githubusercontent.com/assets/13038185/22358464/2042f41a-e3f4-11e6-815a-67aa3ccb2573.png">

By default, you can only transfer one file at a time within domain. Though there appears to be a command-line tool that gets around this (https://github.com/davidstrauss/google-drive-recursive-ownership). 

Using rclone with drive is as lot better than using gdrive. You still get errors such as the below:
```
2017/01/26 18:18:51 1895.zip: Failed to copy: failed to open source object: bad response: 503: 503 Service Unavailable
2017/01/26 18:18:51 Attempt 1/3 failed with 3 errors and: failed to open source object: bad response: 503: 503 Service Unavailable
2017/01/26 18:18:53 Local file system at /Users/leviboxell/desktop/teset/drive/data: Waiting for checks to finish
2017/01/26 18:18:53 Local file system at /Users/leviboxell/desktop/teset/drive/data: Waiting for transfers to finish
2017/01/26 18:18:57 Attempt 2/3 succeeded
```
but rclone automatically retries, which seems to overcome the issues we typically see. The download times using rclone for dropbox vs drive are roughly similar (when testing on hein-bound raw data), with dropbox being slightly faster.

Dropbox interface is more intuitive (no requirement to transfer 'shared' files to 'my drive'). Dropbox ownership is better suited for the labs purposes as everything is 'Matts', instead of everything being owned by whoever uploaded it and then us having to hack around the issue of transferring ownership recursively.

So drive doesn't appear to be as bad as we thought, but dropbox still seems like the better solution (ignoring cost). The best choice seems to ultimately come down to file ownership issues vs cost, and it seems like file ownership is an important enough issue to make dropbox worthwhile. 

One small thing about rclone is that it doesn't appear to allow you to download a specific revision of a file. This shouldn't impact how we do our cache or release protocols, but it does  limit our ability to specify a specific revision of raw data. If space is unlimited, then this shouldn't matter as we can always just create new versions of data in separate folders if we need to and specify these manually.

**Comment by arosenbe** [comment]
@lboxell, I've seen you demonstrate how well rclone works, but I'd like to try it for myself---locally,  on RCC, and on Sherlock. Maybe you could provide a markdown with installation and configuration settings. That would also give me a bit more to review.

**Comment by lboxell** [comment]
@arosenbe,

Below is the information that I would think is necessary to house somewhere for someone who wants to use rclone. I'm not sure the optimal place to put this. The RA Manual + computer build sheet? I don't think it makes sense in the template because its not a requirement there.

Usage:
See [here](http://rclone.org/docs/)

Regular installation:
See [here](http://rclone.org/install/)

Cluster installation:
```
curl -O http://downloads.rclone.org/rclone-current-linux-amd64.zip
unzip rclone-current-linux-amd64.zip
cd rclone-*-linux-amd64
mkdir /home/$USER/.rclone/bin
cp rclone /home/$USER/.rclone/bin
chmod 755 /home/$USER/.rclone/bin/rclone
PATH=$PATH:/home/$USER/.rclone/bin # Might want to add this permenantly
```

**Comment by arosenbe** [comment]
I think the RA manual should have instructions and the computer build sheet should automate as much of the installation as feasible. It took me a few minutes to figure out the configuration procedure, so that might be nice to include in the RA manual. Same with the cluster installation. 

I also tried all but the last line of the cluster installation on RCC and was unable to install rclone. Maybe you have some thoughts? Here's the message
```
[arosenbe@midway-login1 ~]$ curl -O http://downloads.rclone.org/rclone-current-linux-amd64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4115k  100 4115k    0     0   956k      0  0:00:04  0:00:04 --:--:-- 1101k
[arosenbe@midway-login1 ~]$ unzip rclone-current-linux-amd64.zip
Archive:  rclone-current-linux-amd64.zip
   creating: rclone-v1.35-linux-amd64/
  inflating: rclone-v1.35-linux-amd64/README.html  
  inflating: rclone-v1.35-linux-amd64/rclone  
  inflating: rclone-v1.35-linux-amd64/rclone.1  
  inflating: rclone-v1.35-linux-amd64/README.txt  
[arosenbe@midway-login1 ~]$ cd rclone-*-linux-amd64
[arosenbe@midway-login1 rclone-v1.35-linux-amd64]$ mkdir /home/$USER/.rclone/bin
mkdir: cannot create directory `/home/arosenbe/.rclone/bin': No such file or directory
[arosenbe@midway-login1 rclone-v1.35-linux-amd64]$ cp rclone /home/$USER/.rclone/bin
cp: cannot create regular file `/home/arosenbe/.rclone/bin': No such file or directory
[arosenbe@midway-login1 rclone-v1.35-linux-amd64]$ chmod 755 /home/$USER/.rclone/bin/rclone
chmod: cannot access `/home/arosenbe/.rclone/bin/rclone': No such file or directory
```

 I'd also like to know if you could successfully install rclone on Sherlock.

**Comment by lboxell** [comment]
@arosenbe,

I fixed the instructions, the error was simply because the code was trying to make directories recursively. It also works on Sherlock.

I don't really see the point of replicating what is on the rclone.org website in the RA manual. I can see adding a pointer to the rclone website in the RA manual and agree that we can add it to the computer build sheet (we can simply note it in https://github.com/gslab-econ/admin/issues/89 and update everything at once).

**Comment by arosenbe** [comment]
Cool. Sounds good. Cleared to close.

**Comment by lboxell** [comment]
@jmshapir @gentzkow,

FYI, we found out in this task that Drive probably isn't as bad as we thought it was. Some of our issues seem to be fixed by switching from gdrive to rclone for our CLI with google drive. 

However, there are still permission issues with drive that dropbox business takes care of (such as drive prohibiting permission transfers across domains [e.g., stanford --> brown] and not appearing to have a way to natively transfer permissions recursively [there is a 3rd party chrome app thats supposed to help you do this]) and rclone fixes some of the drive issues by simply re-starting on download failures, while we didn't experience any download failures with dropbox. 

So it seems like dropbox is still better than drive (ignoring price differences), but they are closer than we previously thought. I'm guessing this doesn't change our decision to continue with dropbox over drive, but let me know if otherwise.

Also, assuming we continue with Dropbox, we are planning on using the rclone CLI (http://rclone.org/) for interfacing with dropbox instead of creating our own tools (as this task was originally designed to do). Rclone doesn't appear to allow downloading a specific revision, but this doesn't seem necessary for most of cloud storage workflow (the one exception is if we want to use revisions for downloading raw data). Let me know if you think the ability to download specific revisions is worth investing more time in developing our own interface.

**Comment by jmshapir** [comment]
@lboxell I'll defer to @gentzkow here but @gentzkow can let me know if he wants me to weigh in

**Comment by gentzkow** [comment]
Thanks @lboxell. I would vote we not reconsider Google Drive. I'm happy with the Dropbox solution.

I do think the ability to download specific revisions is very valuable. I also think it would be ideal if we don't embed the rclone vs other tools decision too deeply into our scons library / workflow -- ideally, different users could be choosing different tools to do the downloading and everything would work fine.

Maybe we should discuss at Noodles this week?

**Comment by lboxell** [comment]
@gentzkow,

I agree it would probably be good to discuss at noodles tomorrow.

Some thoughts for discussion:
 - Currently, the only place where we would want to download specific revisions is when using raw data that is not derived from another repo (our current release protocol already takes care of versioning). In #27, I have code that will check whether the size, time stamp, or name from dropbox has changed since the last download, which doesn't allow you to specify an old version, but it should inform you when versions change.
 - Given a repo, I don't see a great way to integrate raw data downloading into the scons framework  _and_ allow people to use whatever tool they want to do the raw data download. If we want flexibility of tools across repos, then building a tool that we, as a lab, tend to use shouldn't impede others from using their own tool if they want.

**Comment by gentzkow** [comment]
Thanks @lboxell. I look forward to discussing tomorrow.
-- 

Matthew Gentzkow
Professor of Economics
Stanford University

**Comment by lboxell** [comment]
Closing task. 

Summary from task + discussion at Noodles:

 - Stick with Dropbox. (Though google drive isn't as bad when using RClone). 
 - We probably don't need to create our own dropbox builder, as RClone works pretty well.
 - We are unsure whether we want to have the raw data download being part of the scons framework or a manual step that the user does, because we want `scons` to be error free as often as possible and the data download process had tended to be error prone in the past.
