### ISSUE TITLE
Incorporate matlab builder

### ISSUE THREAD

**Issue by jmshapir** [gslab-econ/gslab_python#53]
As far as I know we don't yet have a matlab builder for scons. I wrote a rudimentary one for my course. 
It is attached here: [build_matlab.txt](https://github.com/gslab-econ/gslab_python/files/737134/build_matlab.txt)

The purpose of this issue is to improve it and fold it into our library.

I've assigned to everyone but feel free to shuffle around as you like.

**Comment by lboxell** [comment]
Closing task.

Summary:
 - Created matlab builder and tested on mac. Jesse will test on matlab at some later point and open up a task if there are issues.
 - New release: https://github.com/gslab-econ/gslab_python/releases/tag/v3.0.4
