### ISSUE TITLE
Test 4.0 on Mac 

### ISSUE THREAD

**Issue by lboxell** [gslab-econ/gslab_python#62]
See https://github.com/gslab-econ/gslab_python/issues/58#issuecomment-295779749

**Comment by arosenbe** [comment]
I've removed everything we list as a dependency and will now try to get template running again.

**Comment by arosenbe** [comment]
I'll use this comment to track installation errors in sequential order

**Comment by arosenbe** [comment]
I'll use this comment to make user-experience type sugegstions

*  The empty list at the end of this line looks ugly

```
scons_debrief(["state_of_repo.log"], [])
```

**Comment by arosenbe** [comment]
See #58 [comment](https://github.com/gslab-econ/gslab_python/issues/58#issuecomment-295959587) for continuing work.
