### ISSUE TITLE
Discuss integration of SQL with SCons

### ISSUE THREAD

**Issue by arosenbe** [gslab-econ/gslab_python#74]
The goal of this issue is to discuss ways to integrate SQL queries executed against an external database into the SCons build framework.

**Comment by arosenbe** [comment]
@mirajshah has put some (really good) work into this problem already. Here's a high-level overview of the method: 

> The main tool we have developed is what we call the "SQLTable Node". As you probably know, SCons arranges Nodes (files, python values, builder functions) into a DAG based on the source/target relationships specified in the SConstruct/SConscript files. A SQL Table can be treated very much like a file object in that it has a unique name by which it can be addressed, contains data that can be checksummed, and actions on it affect its timestamp. 

> The internals of SCons are object-oriented, so there is an abstract "Node" class which specify a series of functions that are called to interact with any Node in the dependency graph/DAG. The "File" class implemented in SCons inherits functionality from the abstract "Node" and overrides certain functions (checking existence, taking a checksum, getting the timestamp, deletion)  to interact with the file system. 

> Our main contribution is to have implemented another subclass of "Node" which we call the "SQLTable". Such a SQLTable Node can be created using a SQLTable() factory method, which parses the name of your intended table and returns a SQLTable Node. Thus SQL Tables can transparently be specified in lists of sources and targets since they confirm to the Node interface, and other basic configuration items (e.g. what builder to use, what directory to build, whether SCons decides based on MD5 checksums or timestamps) are completely decoupled from this somewhat strangely-engineered interaction with the database.

> A cool side-effect of this kind of object-oriented implementation is that it theoretically opens the door to implement many other types of Nodes, for example a "GoogleDoc" Node or a "WebPage" Node.

**Comment by arosenbe** [comment]
@RoyalTS, see the https://github.com/gslab-econ/gslab_python/issues/74#issuecomment-316185600 above and feel free to put questions/insights here directly.

**Comment by RoyalTS** [comment]
Thanks for the intro and all the information about what you guys have already come up with!

I'm currently involved in a project that involves TBs worth of data stored in AWS S3 that are then aggregated into intermediate tables stored in an AWS Redshift database. Even these intermediate tables are still extremely large and so it seems like doing at least some of the computation in DB rather than pulling the data and doing it in R might be a good idea. I am looking for a way to make that workflow as reproducible as I possibly can.

If you guys would be willing to share the `SQLTable Node` code, I would happily try it out and contribute any improvements should we decide that the solution works for us as well.

**Comment by mirajshah** [comment]
Hi @RoyalTS, @arosenbe, I just received an update today that some of our technical lab staff here that they are formally setting up a presence on GitHub and have decided on how to release and license several tools, including the SQLTable Node. I believe I should be able to direct you both to it in the next 2 weeks or so.  Thanks for your patience on this!

**Comment by arosenbe** [comment]
No new information yet.

**Comment by arosenbe** [comment]
No new information yet.

**Comment by arosenbe** [comment]
See a description of an integration between SCons and SQL at https://github.com/gslab-econ/gslab_python/issues/74#issuecomment-316185600. I'll reopen and update if any updates are made per https://github.com/gslab-econ/gslab_python/issues/74#issuecomment-318244820.
