### ISSUE TITLE
Make sure installation instruction removes older gslab_tools packages

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#78]
Particularly `python setup.py install clean`. May have to look into the directory where `pip install` goes. Limited within Python distribution.

**Comment by lboxell** [comment]
@stanfordquan @arosenbe,

Pip naturally removes older versions. Should we just tell users to install via pip? And maybe add a note about the other method but that it doesn't remove older installations which can cause issues with version changes?

**Comment by stanfordquan** [comment]
Do you know why we had the `python setup.py install clean` instruction originally?

**Comment by lboxell** [comment]
It is easier to use when you're testing locally and debugging. Otherwise, you have to push to github and then pip install.

**Comment by stanfordquan** [comment]
I see. In that case I vote for switching the two methods (promote the `git install` and note the option to do `python setup.py install clean` with its caveats)

**Comment by lboxell** [comment]
Closing task.

Pull request: https://github.com/gslab-econ/gslab_python/pull/79
