### ISSUE TITLE
Find way to speed up log.py

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#85]
The following code snipper in `log.py` is quite slow when there's a very large `build`. 

```
    for root, dirs, files in os.walk(parent_dir): # take a walk in parent and child dirs
        for f in files:
            print (root, dirs, f)
            if f.endswith("sconscript.log"):
                f_full = os.path.join(root, f)
```

My instinct is that there are two ways you can speed this up: 1) search targets in `sconscript` for directory and only look in those directory, and then use `grep` 2) use `grep` at the top directory.

I think this should be quick, if there indeed is a faster way. If not I think we may want to delay this beyond 4.0 and build in a mechanism allowing you to not search for logs in certani directory, or skip logging in some runs.

**Comment by lboxell** [comment]
Is the purpose of combining these logs so we have some form of the logs in version control? (If not, I don't see their purpose.)

**Comment by stanfordquan** [comment]
@lboxell there were discussions about how we should present the logs to make it easy for the user as well as for version control purpose. See the pull request [here](https://github.com/gslab-econ/gslab_python/pull/47).

The improvement of this logging mechanism over v3 is that it's substantially easier for a user to see the logs in which their build steps failed.

**Comment by arosenbe** [comment]
@stanfordquan, I have an implementation using CL tools that works on mac. I'd like to use your machine to 
* Test it on Windows
* See if it's "fast enough" in your large repo.

**Comment by arosenbe** [comment]
Definitely fast enough. Went through the entire large repo in less than two seconds on Mac.

**Comment by stanfordquan** [comment]
Confirmed that this is super fast.

**Comment by arosenbe** [comment]
Under PR by @stanfordquan at #87.
