### ISSUE TITLE
Update notes on release.py

### ISSUE THREAD

**Issue by arosenbe** [gslab-econ/gslab_python#88]
The notes on [release.py](https://github.com/gslab-econ/gslab_python/blob/be3e5342aa74a38a94a2b8d85122e528ff670d27/gslab_scons/README.md) have fallen out of sync with the code. (They still mention Google Drive!). The goal of this task is to bring them up to date.

**Comment by arosenbe** [comment]
Some of the [documentation](https://github.com/gslab-econ/gslab_python/blob/be3e5342aa74a38a94a2b8d85122e528ff670d27/gslab_scons/release.py#L26) also seems to be out of date.

**Comment by stanfordquan** [comment]
Good catch @arosenbe . The two commits above should have taken care of it.

**Comment by arosenbe** [comment]
Summary comment. Updates documentation in release.py and its readme.
