### ISSUE TITLE
Address concerns about builder logs and SCons targeting

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#94]
Builder logs are versioned but not targets. So pulling from the cache on a clean clone makes it look like all the logs were deleted.
Determine if we specify logs as targets.
Is there a one-to-one mapping between build steps and logs? Do we allow this mapping to be broken? Allow folder to be excluded in builder log searches.
What is the default name scheme for logs, and how flexible is it? Do we allow users to overwrite/customize just the name or the path as well (probably yes to both)?

**Comment by stanfordquan** [comment]
1) Builder logs are located where the output of a folder is, so whether they are being versioned depends on whether that folder is versioned. 
    - If the folder is versioned, then you never need to pull anything from cache, so this is not a concern. 
    - If the folder is *not* versioned, I don't see a significant cost of not having a `SConscript.log` when you pull from `cache`. The build obtained from `cache` has to be consistent with the code currently in the directory (required by SCons to have the same build signature). 
    - The issue with setting builder logs as targets and then caching them is that you break 1-1 mapping between source code and target, since builder logs contain:
        - Timestamps (this is our own doing)
        - Local machine information (e.g. Stata version, local directory names. This is unavoidable)

So I recommend against targeting/versioning builder logs.  

2) There can and should be a one-to-one mapping between build steps and logs, but it is not enforced. We specify a build step as followed:

```python
env.BuildR(target  = ['#%s/data_r.txt'    % build],
           source  = ['#%s/create_data.r' % source],
           log_ext =  'create_data_r')
```

This logs the build step to `<build>/sconscript_create_data_r.log`. Absent this argument, the build step is logged to `<build>/sconscript.log`. 1-1 mapping is ensured when the user is conscious about which logs they are writing to which output folder, but not otherwise. 

So moving forward, there are two things to be done:

- Allowing the output log to be in a "free location" that is not the target directory, by way of a `log_location` argument to be passed the same way `log_ext` is passed.

- When the `sconstruct.log` maker search the directory for recently-created `sconscript.log` to be appended, allow certain folders to be excluded, by way of an argument when calling `end_log` at the end of the SConstruct.


@yuchuan2016 @Shun-Yang can either of you confirm my impressions and comment on my plan above before I ping PIs? Thanks!

**Comment by stanfordquan** [comment]
Note: improve IOError when  ` # move top level logs to /release/ directory.`

**Comment by yuchuan2016** [comment]
@stanfordquan , I'm not super familiar with the logging mechanism. See my comments below.
- I agree that we should not specify log file as targets. As you said, with the same source, everything in targets should be the same regardless of machine/time. Specifying logs as targets will violate this principle.
- Currently we force the log names to begin with `sconscript` and use `sconscript.log` as default. I would prefer that the default log name is the same as the script (the first source file). So if users have two builders in the same directory, and do not change the default log names, the later one won't overwrite the first one.
- I prefer that log files live in the same place as the targets. I see benefits when users want to collect all logs in the same directory. My concern is that if we send two log files from different builders with the same name to the same location, one would be overwritten. Even if we implement my comment in point 2, no builders in the same directory would produce log file with the same name, we may still have something like `dir1/analysis.do` and `dir2/analysis.do`.

**Comment by stanfordquan** [comment]
I see @yuchuan2016 . 

I prefer that logs produced by `gslab_scons` be prefixed with `sconscript` and end with `.log` because that visually distinguish these logs with other logs which may or may not be produced by other programs. If the user wants to make it different for logs between `analysis.do` and `descriptive.do` she can use `log_ext`. 

I'm fine with not allowing `log_location`. I don't see that being super useful anyway.

**Comment by yuchuan2016** [comment]
@stanfordquan , thanks! Can we have the default name set as `sconscript_`+ source script name + `.log`? In that way, no log will be overwritten even if user do not specify `log_ext`.

**Comment by stanfordquan** [comment]
Cool! I prefer the current implementation (opt-in rather than opt-out). @Shun-Yang you're the tiebreaker! (until PIs vetoed)

**Comment by Shun-Yang** [comment]
@stanfordquan @yuchuan2016 , is the question that what name should the log file be? My opinion is to leave it as is (i.e. sconscript.log + log_ext). I don't think there are many scenarios we call multiple builders from the same directory. And even in that scenario `log_ext` is sufficient in my opinion.

**Comment by stanfordquan** [comment]
Pull request opened in #115
