### ISSUE TITLE
Builders should check whether specified targets exist post-run

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#95]
Determine if we raise an error or warning.
Implement the decision.

**Comment by Shun-Yang** [comment]
My proposal is to raise an error. I can't see a scenario where we are okay with some targets not generated (in that case, we don't need to specify those targets in the first place). Someone [here](https://stackoverflow.com/questions/45096365/fail-if-target-was-not-generated) seems to try to do the same thing. Let me know if you see this differently @stanfordquan @yuchuan2016.

**Comment by stanfordquan** [comment]
I agree that raising the error is the way to go.

Should it be raised after a build step or after the complete build (`atexit`?) We're loading a lot of stuff into `atexit`, so we may want to abstract that out to an `atexit` function suite.

**Comment by yuchuan2016** [comment]
I agree. Shall we add this in `scons_debrief`?

**Comment by Shun-Yang** [comment]
@stanfordquan  I would propose to raise an error after a build step instead of the complete build, as there is no need to continue building if an error arises.  @yuchuan2016 , What is `scons_debrief` and where I can find info on that?

**Comment by yuchuan2016** [comment]
Sorry for the confusion. It's a function in gslab_scons.misc. But if we want to raise error after each step, then it's of no use.

**Comment by Shun-Yang** [comment]
Closing the issue. Pull request is at #110. 
Summary: I added a functionality to check if prespecified target files exit or not after run. If not, an specific error will arise for the user.
