### ISSUE TITLE
Write Anything builder

### ISSUE THREAD

**Issue by stanfordquan** [gslab-econ/gslab_python#97]
Use SCons's env.Command functionality to allow arbitrary build steps with our logging functionality.

**Comment by stanfordquan** [comment]
[Another instance of searching for Scons help returning the gslab-econ/ra-manual.](https://www.google.com/search?q=does+scons+rerun+if+%22env%22+change+environment&oq=does+scons+rerun+if+%22env%22+change+environment&gs_l=psy-ab.3..33i21k1.5357.6538.0.6617.12.12.0.0.0.0.148.1063.5j5.10.0....0...1.1.64.psy-ab..2.9.915...33i160k1.XAWxObcFAxc). We're approaching gslab singularity.

**Comment by stanfordquan** [comment]
@gentzkow 

Hi Matt. The anything builder that I came up with use a `do` argument in the environment passed to the builder to read what the code it should run in the terminal is. However this is bad because when this `do` argument change, Scons does not recognize that the action has changed.

I see three options:

- Force user to write down this `do` argument in a script (does not have to be `sh`, can be anything). The builder reads this script as a source and execute it verbatim. In the below example, this script would just be one line `statamp -e source/analysis/analysis.do`.

- Abandon this `Anything` builder and instead have a `sh` builder and  a `cmd` builder that run shell/batch code. This will be in the same spirit as our Python builder, with code extension check, so forth.

- Leave as is.

I think the first one is ideal, since the user can conceivably have things they can't call with `sh` or `batch`. Please let me know if you disagree.

```
env.BuildAnything(target = ['#%s/plot.pdf'    % build,
                            '#%s/table.txt'    % build],
                  source = ['#%s/analysis.do' % source],
                  do = 'statamp -e source/analysis/analysis.do')
```

**Comment by gentzkow** [comment]
Hmm. I would have thought we want the builder to replicate as closely as possible what the Command builder does, with the added logging. Can we not keep the syntax identical to the Command builder?

**Comment by stanfordquan** [comment]
@gentzkow,

I read into the `env.Command` a bit more --- what it does is that it generates a custom builder, with the custom `action` at the heart of the custom builder. I followed that approach, the syntax is now 

```python
gs.build_anything(target = ['#%s/data.txt'    % build],
                  source = ['#%s/create_data.do' % source],
                  action = 'stata-mp -e source/anything/create_data.do',
                  env    = env) # only showing mandatory arguments
```

The `env` argument has to be there because it's not automatically passed
, whereas `env.Command` is an env method of the `env` object. `env.Command` syntax is

```python
env.Command(target = ['#%s/data.txt'    % build],
            source = ['#%s/create_data.do' % source],
            action = 'stata-mp -e source/anything/create_data.do')
```

The syntax is a bit more cumbersome but the behaviour is closer to `env.Command`, since it defines a custom builder everytime it is called. That means if you change the `action`, SCons sees the object as a different builder and a different node. 

We can't use the current approach for the R, Stata... builders because those builder are, from SCons' point of view, the same action each time it's called, just with different sources/targets.

**Comment by gentzkow** [comment]
This looks like a good solution to me @stanfordquan. Thanks.

**Comment by stanfordquan** [comment]
Thanks! Pull request in #114.
